# 事情的起因：
在一台崭新的服务器上部署sock-shop，运行完部署文件以后查看svc和pod发现都是正常的状态，然后开心的在浏览器访问localhost：30003。。。。。漫长的等待啥子也没有；然后在节点上试验了一下，发现只能显示一部分（标头）。这个问题以前也遇见过，当时情景跟这个差不多，原因是配置文件有问题，没有修改对导致selctor找不到对应服务，拼接不起来一个完整的服务。因此此时怀疑是连接上的问题。由于肯定配置文件是正确的，所以肯定是网络连接出现了问题，而且曾经docker ps -a的时候就发现有一个calico的容器停止了。

## 解决方法1：

参考：https://blog.csdn.net/nklinsirui/article/details/109424100

怀疑是网络原因，本例中的Kubernetes集群用的是Calico网络组件。

### 检查Calico

```bash
# Check daemonset 
kubectl get ds -n kube-system -l k8s-app=calico-node

# Check pod status and ready
kubectl get pods -n kube-system -l k8s-app=calico-node

# Check apiservice status
kubectl get apiservice v1.crd.projectcalico.org -o yaml
```

发现`calico-node`的2个Pod都不是READY状态。

查看`calico-node` Pod的详细信息：

```bash
kubectl describe -n kube-system pod -l k8s-app=calico-node
```

查看`calico-node` 某个Pod的日志：

```bash
kubectl logs -f -n kube-system calico-node-<hash>
```

发现错误日志为：“*calico/node is not ready: BIRD is not ready: BGP not established*“

在Calico的Manifest中的 “# Auto-detect the BGP IP address.” 前添加：

```yaml
# Specify interface
- name: IP_AUTODETECTION_METHOD
  value: "interface=eno2"
```

说明：

- `interface=eth0` 表示选择节点机器的`eth0`网卡，可以通过`ip addr show`来查看网卡。
- **这个服务器的网卡命名改了，是eno2**

一个完整的Calico Manifest的例子参见：

- [calico-eth-ens.yaml](https://github.com/cookcodeblog/k8s-deploy/blob/master/kubeadm_v1.19.3/calico/calico-eth-ens.yaml)

`interface`示例：

```bash
# 指定某个网卡
interface=eth0
interface=ens33

# 指定网卡的前缀
interface=eth.*
interface=ens.*

# 指定多个网卡的前缀
interface=eth.*,ens.*

```

> calico_ip_autodetection_method`: This parameter is used to select  the interface on the node, and for pod to pod data communication across  the nodes. Three methods are available to help select the data path for  pods.

参见：

- https://www.ibm.com/support/knowledgecenter/SSBS6K_3.1.1/manage_network/calico.html
- https://docs.projectcalico.org/networking/ip-autodetection

更新Calico，再重新检查Calico。

再在busybox中测试通过服务名访问成功。

## 解决方法2：
登录浏览器只显示一部分的还有另外一种情况就是数据库没有成功连接。。。

### 排查过程：

首先看一下是哪个server访问不通。直接cluster-ip+port浏览器输入。

```shell
root@cnu101-System-Product-Name:~# kubectl get svc -n sock-shop
NAME           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
carts          ClusterIP   10.104.13.127    <none>        80/TCP         297d
carts-db       ClusterIP   10.103.26.239    <none>        27017/TCP      297d
catalogue      ClusterIP   10.101.12.52     <none>        80/TCP         297d
catalogue-db   ClusterIP   10.104.37.102    <none>        3306/TCP       297d
front-end      NodePort    10.106.115.213   <none>        80:30003/TCP   297d
orders         ClusterIP   10.103.201.221   <none>        80/TCP         297d
orders-db      ClusterIP   10.101.130.7     <none>        27017/TCP      297d
payment        ClusterIP   10.109.151.80    <none>        80/TCP         297d
queue-master   ClusterIP   10.96.80.55      <none>        80/TCP         297d
rabbitmq       ClusterIP   10.109.113.59    <none>        5672/TCP       297d
shipping       ClusterIP   10.97.101.144    <none>        80/TCP         297d
user           ClusterIP   10.106.30.217    <none>        80/TCP         297d
user-db        ClusterIP   10.109.107.118   <none>        27017/TCP      297d
```

这次首先catalogue访问不通，那么就可以去看看对应的容器是谁，然后去看容器日至。

```shell
root@cnu101-System-Product-Name:~# docker ps -a | grep catalogue
e4a492223fcf        weaveworksdemos/catalogue-db:0.3.0                              "docker-entrypoint.s…"   7 months ago        Up 6 hours                  3306/tcp                                                   docker-compose_catalogue-db_1
285620a47139        weaveworksdemos/catalogue:0.3.5                                 "/app -port=80"          7 months ago        Up 6 hours                  80/tcp                                                     docker-compose_catalogue_1

```

发现日至上报错连接数据库失败

```shell
docker logs 285620a47139
Abs(images): "/images" (<nil>)
Getwd: "/" (<nil>)
ls: ["images/WAT.jpg" "images/WAT2.jpg" "images/bit_of_leg_1.jpeg" "images/bit_of_leg_2.jpeg" "images/catsocks.jpg" "images/catsocks2.jpg" "images/classic.jpg" "images/classic2.jpg" "images/colourful_socks.jpg" "images/cross_1.jpeg" "images/cross_2.jpeg" "images/holy_1.jpeg" "images/holy_2.jpeg" "images/holy_3.jpeg" "images/puma_1.jpeg" "images/puma_2.jpeg" "images/rugby_socks.jpg" "images/sock.jpeg" "images/youtube_1.jpeg" "images/youtube_2.jpeg"]
ts=2021-09-01T00:46:59Z caller=main.go:108 Error="Unable to connect to Database" DSN=catalogue_user:default_password@tcp(catalogue-db:3306)/socksdb
ts=2021-09-01T00:46:59Z caller=main.go:136 transport=HTTP port=80
```

因为以前连接时没有问题的，所以首先考虑重新启动服务。

```shell
root@cnu101-System-Product-Name:/home/cnu101/sock_shop/microservices-demo-master/deploy/kubernetes# kubectl replace --force -f complete-demo.yaml -n sock-shop
```

问题解决。。。

# 事情的起因：
使用`istioctl kube-inject -f <your-app-spec>.yaml | kubectl apply -f -`对部署的服务注入边车，然后报错，权限不够！！！P.S.这次的istio安装包使用的是从u盘拷贝过来的。

## 解决方法：
修改istio安装包的权限，`chmod -R 777 istio`


# 事情的起因：
安装istio后启用istio自带的zipkin或者采用自己安装zipkin的方法都无法获得调用信息。
## 解决方法：
### 1.开启所有节点的ssh
1.首先查看各个节点是否都开启了远程访问功能。
`ps -e | grep ssh` 如果只有ssh-agent表示没有启动。
2.安装
`apt-get install openssh-server`
3.使用 1 中的命令查看是否启用了。手动启动的命令(参考)`sudo /etc/init.d/ssh start` 或者重启电脑
4. 远程访问一下试试
### 2.修改zipkin部署文件将service type改为NodePort
```shell
#提取zipkin的部署文件到istio-zipkin.yaml
kubectl get svc zipkin -n istio-system -o yaml>istio-zipkin.yml
#修改文件后执行
kubectl replace -f istio-zipkin.yml
#单独修改一个service或deployment和virtualservice也可以
```
### 3.关闭浏览器的缓存


